### ISSUE TITLE
integration requirements not met by AMU

### ISSUE THREAD

**Issue by giodegas** [EMICVL/AMU#2]
Here I report requirements numbers that are not met by the AMU submitted file to intregrate:

1. The Unity project is not edited with the Unity 2017.1.1f1. Please, download the specific Unity version from the [Unity Archive](https://unity3d.com/get-unity/download/archive)
3. It has not been exported as package
6. The folder structure is not compliant
7. There is a lot of extra content not taken out
13. No license file is found

**Comment by ZaurHajiyev** [comment]
Dear Giovanni, in Baku we agreed on version 5.6.0 for the unit. Now you have changed the version. So we will always change the version?. I'll try to upgrade to the new version.

My package in https://github.com/EMICVL/AMU  or 

https://drive.google.com/drive/folders/0B54fhRLZZXxnaVFnRHBZeW5pd0U





--------------------------------------------
On Tue, 11/7/17, Giovanni De Gasperis <notifications@github.com> wrote:

 Subject: Re: [EMICVL/AMU] integration requirements not met by AMU (#2)
 To: "EMICVL/AMU" <AMU@noreply.github.com>
 Cc: "Hajiyev Zaur" <upfeh@yahoo.com>, "Assign" <assign@noreply.github.com>
 Date: Tuesday, November 7, 2017, 12:44 AM
 
 Assigned #2 to @ZaurHajiyev.
 
 —
 You are receiving this because you were
 assigned.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by giodegas** [comment]
Please check the [integration requirements](http://github.com/EMICVL/ProjectDocumentation/blob/master/Integration_requirements.md) that were approved in the Odessa meeting in October,
since they will be responsibile to make the final integrated prototype.

**Comment by giodegas** [comment]
Also in case you submit as an external link to other cloud storage services (like Google Drive) , please publish the link on the main repository ReadMe.md file and add an MD5 string calculated on the zipped file. 
To do so, you can use the [WinMD5](http://www.winmd5.com) program for windows , or just the 'md5 <file.zip>' command from the Mac terminal.

**Comment by giodegas** [comment]
if you submit you updaded package by today there is still a chance to be integrated in the final prototype.

**Comment by ZaurHajiyev** [comment]
Today we have a holiday - not a working day. I tried to do everything at home. If there is a possibility, please see. Zip file of unity package with 2 part - EMICVL_AMU_Beta 2.0

**Comment by giodegas** [comment]
## Requirements still not met :

6. Content of the level project should have the following structure (folders) to be used in the project:

    * Animation (level animation files)
    * Textures (level texture files)
    * Materials (level material files)
    * Models (models used on the level)
    * Prefabs (prefabs used on the level)
    * Scenes (the game levels including a license text file)
    * Sounds (sound files used on the level)
    * Scripts (scripts used on the level)
    * Sprites (sprites used on the level)
    * Additional assets (as a separate folder including all assets necessary to the scenario to work)

<img width="345" alt="schermata 2017-11-10 alle 06 52 43" src="https://user-images.githubusercontent.com/6838625/32644942-0de11bde-c5e5-11e7-9794-7ae2193f8a9d.png">

Also _Standard Assets_ is still around, toghether with unnecessary extra content that should be taken out , like _Skyboxes_  (point 7). Point 9 requires to have a secondary package like _EMICVL_AMU_Beta2.0_SA.unitypackage_ if _Standard Assets_ are required.

<img width="308" alt="schermata 2017-11-10 alle 07 04 21" src="https://user-images.githubusercontent.com/6838625/32645058-9cbd28de-c5e5-11e7-8d10-6dc7ee699a4d.png">

13. NO LICENSE FILE IS FOUND. The licences should accompany every level project and should be provided to the experts. In order to be part of the packages as Text Asset , save it as a License.txt, then drag and drop inside the Assets/Scene folder in Unity and selected it while creating the export.

**Comment by ZaurHajiyev** [comment]
I tried to do everything as you indicated. Thank you for your help.

**Comment by ZaurHajiyev** [comment]
I tried to do everything as you indicated. Thank you for your help.
If it's not too late, please see.

**Comment by giodegas** [comment]
Getting closer Zaur, but the folder structure is not what is expected. Please have a look at the TSU package structure that is compliant with integration requirements:

![schermata 2017-11-10 alle 15 57 08](https://user-images.githubusercontent.com/6838625/32663939-ffdd8586-c62f-11e7-87ed-0289a70be0b9.png)

You should use the same folder names from the top level.

**Comment by ZaurHajiyev** [comment]
I looked through the TCU file, although there was no big difference, I fixed the structure exactly like they did. In my opinion, the TSU file is not quite workable. Thank you again for your cooperation.

File -  EMICVL_AMU_Beta3.1

**Comment by ZaurHajiyev** [comment]
I looked through the TCU file, although there was no big difference, I fixed the structure exactly like they did. In my opinion, the TSU file is not quite workable. Thank you again for your cooperation.

File -  EMICVL_AMU_Beta3.1

**Comment by giodegas** [comment]
Now integration requirements appear to be met by Beta3. 1

**Comment by giodegas** [comment]
There are heavly conflicts with other team submission assets,  so integration import cannot be completed.
